name: Unpack CuTrim ZIP

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          unzip -o CuTrim_v1_source.zip -d .

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Extract CuTrim source files" || exit 0
          git push
